#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Non-Markovian predictive information generated by hidden finite response.

This script is written for the revised, independent paper.
It does not analyze thermodynamic irreversibility or entropy production.
Primary quantities:
  1. Transfer entropy:
     TE = I(S[t - tau]; S[t + DeltaT] | S[t])
  2. Non-Markovianity index:
     M_nonMarkov = ||P^(2) - P^2||_F / ||P^(2)||_F

Core tests:
  - Analytic linear-Gaussian prediction: TE lag dependence is governed by tau.
  - Nonlinear finite-response simulation: TE and M_nonMarkov peak near DeltaT/tau ~ 1.
  - N x lag ridge: TE optimum remains near tau across spatial resolutions.
  - Mechanistic controls: memory removal, no coupling, no feedback, equilibrium control.
  - Nulls: permutation, shifted-past, and mismatched-lag controls.
  - Robustness: partition scheme and local parameter perturbation.

Run:
  python3 nonmarkov_predictive_information.py

Quick test:
  python3 nonmarkov_predictive_information.py --quick
"""

import argparse
import json
import math
import time
from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple, Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# Configuration
# ============================================================

@dataclass
class Config:
    # Nonlinear finite-response baseline parameter set
    alpha: float = 1.427711
    beta: float = 0.862648
    gamma: float = 0.534251
    kappa: float = 2.427585
    sigma_x: float = 0.588907
    sigma_y: float = 0.588907

    # Stable linear-Gaussian theory parameters
    lin_alpha: float = 1.0
    lin_beta: float = 0.35
    lin_gamma: float = 1.0
    lin_kappa: float = 0.55
    lin_sigma_x: float = 0.35
    lin_sigma_y: float = 0.35

    dt: float = 0.01
    T: float = 4000.0
    burn_min: float = 500.0
    burn_tau_multiplier: float = 20.0
    n_runs: int = 30
    seed: int = 65065

    N_primary: int = 10
    N_values: Tuple[int, ...] = (8, 10, 12, 16, 24, 32)
    lag_ratios: Tuple[float, ...] = (0.1, 0.25, 0.5, 1.0, 2.0, 4.0, 8.0)
    past_lag_ratios: Tuple[float, ...] = (0.1, 0.25, 0.5, 1.0, 2.0, 4.0, 8.0)

    pseudocount: float = 1e-9
    min_outgoing_count: int = 25

    # Nulls
    n_null: int = 300

    # Partition robustness
    partition_methods: Tuple[str, ...] = ("quantile", "equal_width", "mi")
    mi_candidate_count: int = 48
    mi_subsample: int = 20000

    # Controls
    gamma_fast: float = 50.0
    gamma_slow: float = 0.05
    ou_corr_time: float = 0.2

    # Local parameter robustness
    robustness_runs: int = 10
    robustness_factors: Tuple[float, ...] = (0.8, 1.0, 1.2)


def quick_config() -> Config:
    c = Config()
    c.T = 900.0
    c.burn_min = 150.0
    c.n_runs = 4
    c.n_null = 50
    c.N_values = (8, 10, 16)
    c.lag_ratios = (0.25, 0.5, 1.0, 2.0, 4.0)
    c.past_lag_ratios = (0.25, 0.5, 1.0, 2.0, 4.0)
    c.partition_methods = ("quantile", "equal_width")
    c.robustness_runs = 3
    c.robustness_factors = (0.9, 1.0, 1.1)
    return c


# ============================================================
# Plot style
# ============================================================

def set_plot_style() -> None:
    plt.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": 10,
        "axes.labelsize": 11,
        "axes.titlesize": 11,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "legend.fontsize": 9,
        "figure.dpi": 300,
        "savefig.dpi": 600,
        "savefig.bbox": "tight",
        "axes.spines.top": False,
        "axes.spines.right": False,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    })


def savefig(fig, outdir: Path, name: str) -> None:
    fig.savefig(outdir / f"{name}.png", dpi=600)
    fig.savefig(outdir / f"{name}.pdf")
    plt.close(fig)


# ============================================================
# Linear-Gaussian analytic theory
# ============================================================

def expm_2x2(A: np.ndarray, t: float) -> np.ndarray:
    vals, vecs = np.linalg.eig(A)
    E = vecs @ np.diag(np.exp(vals * t)) @ np.linalg.inv(vecs)
    return np.real_if_close(E).real


def solve_ou_covariance(A: np.ndarray, Q: np.ndarray) -> np.ndarray:
    # Solve A Sigma + Sigma A^T + Q = 0.
    n = A.shape[0]
    K = np.kron(np.eye(n), A) + np.kron(A, np.eye(n))
    b = -Q.reshape(-1)
    Sigma = np.linalg.solve(K, b).reshape(n, n)
    return 0.5 * (Sigma + Sigma.T)


def linear_covariance_x(c: Config, h: float) -> float:
    A = np.array([
        [-c.lin_alpha, c.lin_beta],
        [ c.lin_kappa, -c.lin_gamma],
    ], dtype=float)
    Q = np.diag([c.lin_sigma_x ** 2, c.lin_sigma_y ** 2])
    Sigma = solve_ou_covariance(A, Q)
    E = expm_2x2(A.T, abs(h))
    C = Sigma @ E
    return float(C[0, 0])


def gaussian_conditional_te_from_cov(C0: float, Cl: float, Cd: float, Cld: float) -> float:
    # TE = I(X_{t-l}; X_{t+d} | X_t)
    var_past_cond = C0 - (Cl * Cl) / C0
    var_fut_cond = C0 - (Cd * Cd) / C0
    cov_cond = Cld - (Cl * Cd) / C0
    denom = math.sqrt(max(var_past_cond * var_fut_cond, 1e-300))
    rho = cov_cond / denom
    rho = max(min(rho, 0.999999999), -0.999999999)
    return float(-0.5 * math.log(1.0 - rho * rho))


def run_linear_theory(c: Config, tables: Path) -> pd.DataFrame:
    tau = 1.0 / c.lin_gamma
    rows = []
    for lr in c.lag_ratios:
        Delta = lr * tau
        past = tau
        C0 = linear_covariance_x(c, 0.0)
        Cl = linear_covariance_x(c, past)
        Cd = linear_covariance_x(c, Delta)
        Cld = linear_covariance_x(c, past + Delta)
        te = gaussian_conditional_te_from_cov(C0, Cl, Cd, Cld)
        rows.append({
            "lag_ratio": lr,
            "DeltaT": Delta,
            "past_lag": past,
            "TE_gaussian_analytic": te,
        })
    df = pd.DataFrame(rows)
    df.to_csv(tables / "linear_gaussian_theory_TE.csv", index=False)
    return df


# ============================================================
# Simulation
# ============================================================

def compute_steps(c: Config, gamma: float) -> Tuple[int, int, float]:
    tau = 1.0 / gamma
    burn = max(c.burn_min, c.burn_tau_multiplier * tau)
    steps = int(round(c.T / c.dt))
    burn_steps = int(round(burn / c.dt))
    if burn_steps >= steps // 2:
        steps = burn_steps + int(round(max(c.T, 20.0 * tau) / c.dt))
    return steps, burn_steps, tau


def simulate_finite_response(
    c: Config,
    rng: np.random.Generator,
    alpha: Optional[float] = None,
    beta: Optional[float] = None,
    gamma: Optional[float] = None,
    kappa: Optional[float] = None,
    sigma_x: Optional[float] = None,
    sigma_y: Optional[float] = None,
    response: str = "tanh",
    ou_noise: bool = False,
) -> Tuple[np.ndarray, np.ndarray, float]:
    alpha = c.alpha if alpha is None else alpha
    beta = c.beta if beta is None else beta
    gamma = c.gamma if gamma is None else gamma
    kappa = c.kappa if kappa is None else kappa
    sigma_x = c.sigma_x if sigma_x is None else sigma_x
    sigma_y = c.sigma_y if sigma_y is None else sigma_y

    steps, burn_steps, tau = compute_steps(c, gamma)
    x = np.zeros(steps, dtype=np.float64)
    y = np.zeros(steps, dtype=np.float64)
    sqrt_dt = math.sqrt(c.dt)

    if response == "tanh":
        def f(v): return math.tanh(v)
    elif response == "linear":
        def f(v): return v
    else:
        raise ValueError(response)

    if ou_noise:
        rho = math.exp(-c.dt / c.ou_corr_time)
        s = math.sqrt(max(0.0, 1.0 - rho * rho))
        nx = 0.0
        ny = 0.0
        for n in range(steps - 1):
            nx = rho * nx + s * rng.normal()
            ny = rho * ny + s * rng.normal()
            x[n+1] = x[n] + (-alpha * x[n] + beta * f(y[n])) * c.dt + sigma_x * sqrt_dt * nx
            y[n+1] = y[n] + (-gamma * y[n] + kappa * x[n]) * c.dt + sigma_y * sqrt_dt * ny
    else:
        for n in range(steps - 1):
            x[n+1] = x[n] + (-alpha * x[n] + beta * f(y[n])) * c.dt + sigma_x * sqrt_dt * rng.normal()
            y[n+1] = y[n] + (-gamma * y[n] + kappa * x[n]) * c.dt + sigma_y * sqrt_dt * rng.normal()

    return x[burn_steps:], y[burn_steps:], tau


def simulate_equilibrium_control(c: Config, rng: np.random.Generator) -> Tuple[np.ndarray, np.ndarray, float]:
    # Stable detailed-balance linear gradient-flow control.
    a = c.alpha
    b = c.gamma
    coupling = 0.45 * math.sqrt(a * b)
    temp = max(1e-8, c.sigma_x * c.sigma_x / 2.0)

    steps, burn_steps, tau = compute_steps(c, c.gamma)
    x = np.zeros(steps, dtype=np.float64)
    y = np.zeros(steps, dtype=np.float64)
    sqrt_2T_dt = math.sqrt(2.0 * temp * c.dt)

    for n in range(steps - 1):
        x[n+1] = x[n] + (-a * x[n] + coupling * y[n]) * c.dt + sqrt_2T_dt * rng.normal()
        y[n+1] = y[n] + ( coupling * x[n] - b * y[n]) * c.dt + sqrt_2T_dt * rng.normal()

    return x[burn_steps:], y[burn_steps:], tau


# ============================================================
# Coarse-graining
# ============================================================

def quantile_edges(x: np.ndarray, N: int) -> np.ndarray:
    edges = np.quantile(x, np.linspace(0.0, 1.0, N + 1))
    edges = np.asarray(edges, dtype=np.float64)
    for i in range(1, len(edges)):
        if edges[i] <= edges[i-1]:
            edges[i] = edges[i-1] + 1e-10
    edges[0] -= 1e-9
    edges[-1] += 1e-9
    return edges


def equal_width_edges(x: np.ndarray, N: int) -> np.ndarray:
    mn = float(np.min(x))
    mx = float(np.max(x))
    if mx <= mn:
        mx = mn + 1e-9
    edges = np.linspace(mn, mx, N + 1)
    edges[0] -= 1e-9
    edges[-1] += 1e-9
    return edges


def digitize(x: np.ndarray, edges: np.ndarray) -> np.ndarray:
    S = np.digitize(x, edges[1:-1], right=False)
    S[S < 0] = 0
    S[S >= len(edges) - 1] = len(edges) - 2
    return S.astype(np.int64)


def mutual_information_symbols(a: np.ndarray, b: np.ndarray, N: int, pc: float = 1e-12) -> float:
    counts = np.zeros((N, N), dtype=np.float64)
    np.add.at(counts, (a, b), 1.0)
    counts += pc
    pxy = counts / np.sum(counts)
    px = np.sum(pxy, axis=1, keepdims=True)
    py = np.sum(pxy, axis=0, keepdims=True)
    return float(np.sum(pxy * np.log(pxy / (px @ py))))


def mi_edges(x: np.ndarray, N: int, lag_steps: int, c: Config) -> np.ndarray:
    # Greedy partition used only as a robustness check.
    if len(x) > c.mi_subsample:
        idx = np.linspace(0, len(x) - 1, c.mi_subsample).astype(int)
        xs = x[idx]
    else:
        xs = x

    if len(xs) <= lag_steps + 10:
        return quantile_edges(x, N)

    x0 = xs[:-lag_steps]
    x1 = xs[lag_steps:]
    candidates = np.unique(np.quantile(xs, np.linspace(0.02, 0.98, c.mi_candidate_count)))
    thresholds: List[float] = []
    mn = float(np.min(x)) - 1e-9
    mx = float(np.max(x)) + 1e-9

    for _ in range(N - 1):
        best_thr = None
        best_mi = -np.inf
        for thr in candidates:
            if any(abs(float(thr) - t) < 1e-12 for t in thresholds):
                continue
            trial = sorted(thresholds + [float(thr)])
            edges = np.array([mn] + trial + [mx], dtype=np.float64)
            nb = len(edges) - 1
            s0 = digitize(x0, edges)
            s1 = digitize(x1, edges)
            mi = mutual_information_symbols(s0, s1, nb)
            if mi > best_mi:
                best_mi = mi
                best_thr = float(thr)
        if best_thr is None:
            return quantile_edges(x, N)
        thresholds.append(best_thr)

    edges = np.array([mn] + sorted(thresholds) + [mx], dtype=np.float64)
    if len(edges) != N + 1:
        return quantile_edges(x, N)
    return edges


def get_edges(x: np.ndarray, N: int, method: str, lag_steps: int, c: Config) -> np.ndarray:
    if method == "quantile":
        return quantile_edges(x, N)
    if method == "equal_width":
        return equal_width_edges(x, N)
    if method == "mi":
        return mi_edges(x, N, lag_steps, c)
    raise ValueError(method)


# ============================================================
# Metrics
# ============================================================

def transition_counts(S: np.ndarray, lag_steps: int, N: int) -> Tuple[np.ndarray, np.ndarray]:
    lag_steps = max(1, int(lag_steps))
    src = S[:-lag_steps]
    dst = S[lag_steps:]
    counts = np.zeros((N, N), dtype=np.float64)
    np.add.at(counts, (src, dst), 1.0)
    occ = np.bincount(src, minlength=N).astype(np.float64)
    return counts, occ


def counts_to_P(counts: np.ndarray, pseudocount: float) -> np.ndarray:
    N = counts.shape[0]
    C = counts.astype(np.float64).copy()
    if pseudocount > 0:
        C += pseudocount
    row = C.sum(axis=1, keepdims=True)
    P = np.divide(C, row, out=np.ones_like(C) / N, where=row > 0)
    return P


def nonmarkov_measure(S: np.ndarray, lag_steps: int, N: int, pseudocount: float) -> float:
    counts1, _ = transition_counts(S, lag_steps, N)
    P1 = counts_to_P(counts1, pseudocount)
    counts2, _ = transition_counts(S, 2 * lag_steps, N)
    P2 = counts_to_P(counts2, pseudocount)
    pred = P1 @ P1
    den = np.linalg.norm(P2, ord="fro")
    if den <= 1e-15:
        return np.nan
    return float(np.linalg.norm(P2 - pred, ord="fro") / den)


def make_te_arrays(S: np.ndarray, future_steps: int, past_steps: int) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    future_steps = max(1, future_steps)
    past_steps = max(1, past_steps)
    start = past_steps
    stop = len(S) - future_steps
    if stop <= start + 10:
        return np.array([], dtype=int), np.array([], dtype=int), np.array([], dtype=int)
    past = S[start - past_steps:stop - past_steps]
    curr = S[start:stop]
    fut = S[start + future_steps:stop + future_steps]
    return fut.astype(np.int64), curr.astype(np.int64), past.astype(np.int64)


def transfer_entropy_from_arrays(fut: np.ndarray, curr: np.ndarray, past: np.ndarray, N: int, pseudocount: float) -> float:
    if len(fut) == 0:
        return np.nan

    idx3 = fut * (N * N) + curr * N + past
    c_fcp = np.bincount(idx3, minlength=N * N * N).reshape(N, N, N).astype(np.float64)

    c_cp = np.sum(c_fcp, axis=0)  # curr, past
    c_fc = np.sum(c_fcp, axis=2)  # fut, curr
    c_c = np.sum(c_cp, axis=1)    # curr

    total = float(len(fut))
    floor = 1e-300
    te = 0.0

    nz = np.argwhere(c_fcp > 0)
    pc = pseudocount

    for f, cc, p in nz:
        n = c_fcp[f, cc, p]
        p_joint = n / total

        den_cp = c_cp[cc, p] + pc * N
        den_c = c_c[cc] + pc * N
        if den_cp <= 0 or den_c <= 0:
            continue

        p_f_given_cp = max(float((n + pc) / den_cp), floor)
        p_f_given_c = max(float((c_fc[f, cc] + pc) / den_c), floor)

        te += p_joint * math.log(p_f_given_cp / p_f_given_c)

    return float(te)


def transfer_entropy(S: np.ndarray, future_steps: int, past_steps: int, N: int, pseudocount: float) -> float:
    fut, curr, past = make_te_arrays(S, future_steps, past_steps)
    return transfer_entropy_from_arrays(fut, curr, past, N, pseudocount)


def shifted_past_null_TE(S: np.ndarray, future_steps: int, past_steps: int, N: int, pseudocount: float,
                         rng: np.random.Generator, n_null: int) -> np.ndarray:
    fut, curr, past = make_te_arrays(S, future_steps, past_steps)
    if len(fut) == 0:
        return np.full(n_null, np.nan)

    vals = []
    L = len(past)
    for _ in range(n_null):
        shift = int(rng.integers(max(1, L // 10), max(2, L - L // 10)))
        past_shifted = np.roll(past, shift)
        vals.append(transfer_entropy_from_arrays(fut, curr, past_shifted, N, pseudocount))
    return np.asarray(vals, dtype=np.float64)


def permuted_past_null_TE(S: np.ndarray, future_steps: int, past_steps: int, N: int, pseudocount: float,
                          rng: np.random.Generator, n_null: int) -> np.ndarray:
    fut, curr, past = make_te_arrays(S, future_steps, past_steps)
    if len(fut) == 0:
        return np.full(n_null, np.nan)

    vals = []
    for _ in range(n_null):
        vals.append(transfer_entropy_from_arrays(fut, curr, rng.permutation(past), N, pseudocount))
    return np.asarray(vals, dtype=np.float64)


def sequence_permutation_null(S: np.ndarray, future_steps: int, past_steps: int, N: int, pseudocount: float,
                              rng: np.random.Generator, n_null: int) -> Tuple[np.ndarray, np.ndarray]:
    vals_te = []
    vals_nm = []
    for _ in range(n_null):
        Sp = rng.permutation(S)
        vals_te.append(transfer_entropy(Sp, future_steps, past_steps, N, pseudocount))
        vals_nm.append(nonmarkov_measure(Sp, future_steps, N, pseudocount))
    return np.asarray(vals_te), np.asarray(vals_nm)


def stationarity_distance(S: np.ndarray, lag_steps: int, N: int, pseudocount: float) -> float:
    mid = len(S) // 2
    if mid <= 2 * lag_steps:
        return np.nan
    c1, o1 = transition_counts(S[:mid], lag_steps, N)
    c2, o2 = transition_counts(S[mid:], lag_steps, N)
    P1 = counts_to_P(c1, pseudocount)
    P2 = counts_to_P(c2, pseudocount)
    occ1 = o1 / max(np.sum(o1), 1.0)
    occ2 = o2 / max(np.sum(o2), 1.0)
    return float(np.linalg.norm(P1 - P2, ord="fro") + np.linalg.norm(occ1 - occ2))


def metrics_for_x(
    x: np.ndarray,
    c: Config,
    N: int,
    lag_ratio: float,
    tau_ref: float,
    partition: str = "quantile",
    past_ratio: float = 1.0,
) -> Dict[str, float]:
    future_steps = max(1, int(round(lag_ratio * tau_ref / c.dt)))
    past_steps = max(1, int(round(past_ratio * tau_ref / c.dt)))

    edges = get_edges(x, N, partition, future_steps, c)
    S = digitize(x, edges)

    counts, _ = transition_counts(S, future_steps, N)
    min_out = float(np.min(counts.sum(axis=1))) if counts.size else 0.0
    ok = min_out >= c.min_outgoing_count

    te = transfer_entropy(S, future_steps, past_steps, N, c.pseudocount) if ok else np.nan
    nm = nonmarkov_measure(S, future_steps, N, c.pseudocount) if ok else np.nan
    stat = stationarity_distance(S, future_steps, N, c.pseudocount)

    return {
        "N": N,
        "lag_ratio": lag_ratio,
        "past_ratio": past_ratio,
        "future_steps": future_steps,
        "past_steps": past_steps,
        "partition": partition,
        "min_outgoing_count": min_out,
        "min_count_ok": ok,
        "TE": te,
        "M_nonMarkov": nm,
        "stationarity_distance": stat,
    }


def sem(vals: np.ndarray) -> float:
    vals = np.asarray(vals, dtype=np.float64)
    vals = vals[np.isfinite(vals)]
    if len(vals) <= 1:
        return np.nan
    return float(np.std(vals, ddof=1) / math.sqrt(len(vals)))


def summarize(df: pd.DataFrame, group_cols: List[str], metrics: List[str]) -> pd.DataFrame:
    rows = []
    for key, g in df.groupby(group_cols):
        if not isinstance(key, tuple):
            key = (key,)
        row = {col: val for col, val in zip(group_cols, key)}
        row["n"] = len(g)
        for m in metrics:
            vals = pd.to_numeric(g[m], errors="coerce").to_numpy(dtype=np.float64)
            vals = vals[np.isfinite(vals)]
            row[f"{m}_mean"] = float(np.mean(vals)) if len(vals) else np.nan
            row[f"{m}_sem"] = sem(vals) if len(vals) else np.nan
            row[f"{m}_median"] = float(np.median(vals)) if len(vals) else np.nan
        rows.append(row)
    return pd.DataFrame(rows)


# ============================================================
# Analysis stages
# ============================================================

def generate_main_runs(c: Config) -> List[Dict[str, object]]:
    rng_master = np.random.default_rng(c.seed)
    runs = []
    for r in range(c.n_runs):
        rng = np.random.default_rng(rng_master.integers(0, 2**32 - 1))
        x, y, tau = simulate_finite_response(c, rng)
        runs.append({"run": r, "x": x, "y": y, "tau": tau})
    return runs


def run_lag_analysis(c: Config, runs: List[Dict[str, object]], tables: Path):
    tau_ref = 1.0 / c.gamma
    rows = []
    for item in runs:
        for lr in c.lag_ratios:
            rec = metrics_for_x(item["x"], c, c.N_primary, lr, tau_ref)
            rec.update({"run": item["run"]})
            rows.append(rec)
    df = pd.DataFrame(rows)
    df.to_csv(tables / "main_lag_raw.csv", index=False)
    summ = summarize(df, ["lag_ratio"], ["TE", "M_nonMarkov", "stationarity_distance"])
    summ.to_csv(tables / "main_lag_summary.csv", index=False)
    return df, summ


def run_N_lag_analysis(c: Config, runs: List[Dict[str, object]], tables: Path):
    tau_ref = 1.0 / c.gamma
    rows = []
    for item in runs:
        for N in c.N_values:
            for lr in c.lag_ratios:
                rec = metrics_for_x(item["x"], c, N, lr, tau_ref)
                rec.update({"run": item["run"]})
                rows.append(rec)
    df = pd.DataFrame(rows)
    df.to_csv(tables / "N_lag_raw.csv", index=False)
    summ = summarize(df, ["N", "lag_ratio"], ["TE", "M_nonMarkov", "stationarity_distance"])
    summ.to_csv(tables / "N_lag_summary.csv", index=False)

    opt_rows = []
    for metric in ["TE", "M_nonMarkov"]:
        for (run, N), g in df.groupby(["run", "N"]):
            gg = g[np.isfinite(g[metric])]
            if len(gg) == 0:
                continue
            idx = gg[metric].idxmax()
            opt_rows.append({
                "run": run,
                "N": N,
                "metric": metric,
                "optimal_lag_ratio": float(gg.loc[idx, "lag_ratio"]),
                "peak_value": float(gg.loc[idx, metric]),
            })
    opt = pd.DataFrame(opt_rows)
    opt.to_csv(tables / "optimal_lag_by_N_raw.csv", index=False)
    opt_summ = summarize(opt, ["N", "metric"], ["optimal_lag_ratio", "peak_value"])
    opt_summ.to_csv(tables / "optimal_lag_by_N_summary.csv", index=False)
    return df, summ, opt, opt_summ


def run_controls(c: Config, tables: Path):
    rng_master = np.random.default_rng(c.seed + 1000)
    tau_ref = 1.0 / c.gamma
    specs = [
        ("main", "main", {}),
        ("equilibrium_control", "equilibrium", {}),
        ("memory_removal_gamma_fast", "main", {"gamma": c.gamma_fast}),
        ("slow_memory_gamma_slow", "main", {"gamma": c.gamma_slow}),
        ("no_feedback_beta0", "main", {"beta": 0.0}),
        ("no_hidden_coupling_kappa0", "main", {"kappa": 0.0}),
        ("ou_noise", "main", {"ou_noise": True}),
    ]

    rows = []
    for cond, kind, kwargs in specs:
        for run in range(c.n_runs):
            rng = np.random.default_rng(rng_master.integers(0, 2**32 - 1))
            if kind == "equilibrium":
                x, y, _ = simulate_equilibrium_control(c, rng)
            else:
                x, y, _ = simulate_finite_response(
                    c,
                    rng,
                    beta=kwargs.get("beta", c.beta),
                    gamma=kwargs.get("gamma", c.gamma),
                    kappa=kwargs.get("kappa", c.kappa),
                    ou_noise=kwargs.get("ou_noise", False),
                )
            rec = metrics_for_x(x, c, c.N_primary, 1.0, tau_ref)
            rec.update({"run": run, "condition": cond})
            rows.append(rec)

    df = pd.DataFrame(rows)
    df.to_csv(tables / "controls_raw.csv", index=False)
    summ = summarize(df, ["condition"], ["TE", "M_nonMarkov", "stationarity_distance"])
    summ.to_csv(tables / "controls_summary.csv", index=False)
    return df, summ


def run_null_models(c: Config, runs: List[Dict[str, object]], tables: Path):
    rng = np.random.default_rng(c.seed + 2000)
    tau_ref = 1.0 / c.gamma
    future_steps = max(1, int(round(tau_ref / c.dt)))
    past_steps = future_steps
    N = c.N_primary

    x = runs[0]["x"]
    edges = quantile_edges(x, N)
    S = digitize(x, edges)

    observed_TE = transfer_entropy(S, future_steps, past_steps, N, c.pseudocount)
    observed_M = nonmarkov_measure(S, future_steps, N, c.pseudocount)

    perm_TE, perm_M = sequence_permutation_null(S, future_steps, past_steps, N, c.pseudocount, rng, c.n_null)
    shifted_TE = shifted_past_null_TE(S, future_steps, past_steps, N, c.pseudocount, rng, c.n_null)
    pastperm_TE = permuted_past_null_TE(S, future_steps, past_steps, N, c.pseudocount, rng, c.n_null)

    rows = []
    for name, metric, obs, vals in [
        ("sequence_permutation", "TE", observed_TE, perm_TE),
        ("sequence_permutation", "M_nonMarkov", observed_M, perm_M),
        ("shifted_past", "TE", observed_TE, shifted_TE),
        ("permuted_past", "TE", observed_TE, pastperm_TE),
    ]:
        vals = np.asarray(vals, dtype=np.float64)
        vals = vals[np.isfinite(vals)]
        rows.append({
            "null": name,
            "metric": metric,
            "observed": obs,
            "null_mean": float(np.mean(vals)) if len(vals) else np.nan,
            "null_ci_low": float(np.percentile(vals, 2.5)) if len(vals) else np.nan,
            "null_ci_high": float(np.percentile(vals, 97.5)) if len(vals) else np.nan,
            "p_value": float(np.mean(vals >= obs)) if len(vals) else np.nan,
        })

    raw_rows = []
    for i, v in enumerate(perm_TE):
        raw_rows.append({"null": "sequence_permutation", "metric": "TE", "iter": i, "value": v})
    for i, v in enumerate(perm_M):
        raw_rows.append({"null": "sequence_permutation", "metric": "M_nonMarkov", "iter": i, "value": v})
    for i, v in enumerate(shifted_TE):
        raw_rows.append({"null": "shifted_past", "metric": "TE", "iter": i, "value": v})
    for i, v in enumerate(pastperm_TE):
        raw_rows.append({"null": "permuted_past", "metric": "TE", "iter": i, "value": v})

    raw = pd.DataFrame(raw_rows)
    raw.to_csv(tables / "null_models_raw.csv", index=False)
    summ = pd.DataFrame(rows)
    summ.to_csv(tables / "null_models_summary.csv", index=False)
    return raw, summ


def run_mismatched_lag_analysis(c: Config, runs: List[Dict[str, object]], tables: Path):
    tau_ref = 1.0 / c.gamma
    rows = []
    for item in runs:
        for pr in c.past_lag_ratios:
            # Future lag is fixed at tau; past lag varies.
            rec = metrics_for_x(item["x"], c, c.N_primary, 1.0, tau_ref, past_ratio=pr)
            rec.update({"run": item["run"], "past_lag_ratio": pr})
            rows.append(rec)
    df = pd.DataFrame(rows)
    df.to_csv(tables / "mismatched_past_lag_raw.csv", index=False)
    summ = summarize(df, ["past_lag_ratio"], ["TE", "M_nonMarkov", "stationarity_distance"])
    summ.to_csv(tables / "mismatched_past_lag_summary.csv", index=False)
    return df, summ


def run_partition_robustness(c: Config, runs: List[Dict[str, object]], tables: Path):
    tau_ref = 1.0 / c.gamma
    rows = []
    for item in runs:
        for method in c.partition_methods:
            rec = metrics_for_x(item["x"], c, c.N_primary, 1.0, tau_ref, partition=method)
            rec.update({"run": item["run"], "partition": method})
            rows.append(rec)
    df = pd.DataFrame(rows)
    df.to_csv(tables / "partition_robustness_raw.csv", index=False)
    summ = summarize(df, ["partition"], ["TE", "M_nonMarkov", "stationarity_distance"])
    summ.to_csv(tables / "partition_robustness_summary.csv", index=False)
    return df, summ


def run_local_parameter_robustness(c: Config, tables: Path):
    rng_master = np.random.default_rng(c.seed + 3000)
    tau_ref = 1.0 / c.gamma
    rows = []

    perturbations = []
    for param in ["beta", "kappa", "gamma"]:
        for factor in c.robustness_factors:
            perturbations.append((param, factor))

    for param, factor in perturbations:
        for run in range(c.robustness_runs):
            rng = np.random.default_rng(rng_master.integers(0, 2**32 - 1))
            kwargs = {}
            if param == "beta":
                kwargs["beta"] = c.beta * factor
            if param == "kappa":
                kwargs["kappa"] = c.kappa * factor
            if param == "gamma":
                kwargs["gamma"] = c.gamma * factor
            x, y, _ = simulate_finite_response(c, rng, **kwargs)
            rec = metrics_for_x(x, c, c.N_primary, 1.0, tau_ref)
            rec.update({"run": run, "parameter": param, "factor": factor})
            rows.append(rec)

    df = pd.DataFrame(rows)
    df.to_csv(tables / "local_parameter_robustness_raw.csv", index=False)
    summ = summarize(df, ["parameter", "factor"], ["TE", "M_nonMarkov", "stationarity_distance"])
    summ.to_csv(tables / "local_parameter_robustness_summary.csv", index=False)
    return df, summ


# ============================================================
# Figures
# ============================================================

def plot_theory(theory: pd.DataFrame, figs: Path):
    fig, ax = plt.subplots(figsize=(4.6, 3.2), constrained_layout=True)
    ax.plot(theory["lag_ratio"], theory["TE_gaussian_analytic"], marker="o")
    ax.axvline(1.0, linestyle="--", linewidth=1)
    ax.set_xscale("log")
    ax.set_xlabel("Delta T / tau")
    ax.set_ylabel("Analytic Gaussian TE")
    ax.set_title("Linear-Gaussian prediction")
    savefig(fig, figs, "fig1_linear_gaussian_theory")


def plot_lag_curves(summ: pd.DataFrame, figs: Path):
    df = summ.sort_values("lag_ratio")
    fig, axes = plt.subplots(1, 2, figsize=(7.6, 3.2), constrained_layout=True)

    axes[0].errorbar(df["lag_ratio"], df["TE_mean"], yerr=df["TE_sem"], marker="o", capsize=3)
    axes[0].axvline(1.0, linestyle="--", linewidth=1)
    axes[0].set_xscale("log")
    axes[0].set_xlabel("Delta T / tau")
    axes[0].set_ylabel("Transfer entropy")
    axes[0].set_title("A. Predictive information")

    axes[1].errorbar(df["lag_ratio"], df["M_nonMarkov_mean"], yerr=df["M_nonMarkov_sem"], marker="o", capsize=3)
    axes[1].axvline(1.0, linestyle="--", linewidth=1)
    axes[1].set_xscale("log")
    axes[1].set_xlabel("Delta T / tau")
    axes[1].set_ylabel("M_nonMarkov")
    axes[1].set_title("B. Non-Markovianity")

    savefig(fig, figs, "fig2_primary_lag_curves")


def plot_N_lag_heatmap(summ: pd.DataFrame, figs: Path):
    Ns = sorted(summ["N"].unique())
    lrs = sorted(summ["lag_ratio"].unique())

    def mat(metric: str):
        A = np.full((len(Ns), len(lrs)), np.nan)
        for i, N in enumerate(Ns):
            for j, lr in enumerate(lrs):
                row = summ[(summ["N"] == N) & (summ["lag_ratio"] == lr)]
                if len(row):
                    A[i, j] = float(row.iloc[0][f"{metric}_mean"])
        return A

    TE = mat("TE")
    MN = mat("M_nonMarkov")

    fig, axes = plt.subplots(1, 2, figsize=(8.4, 3.6), constrained_layout=True)
    im0 = axes[0].imshow(TE, origin="lower", aspect="auto")
    axes[0].set_title("A. TE ridge")
    axes[0].set_xlabel("Delta T / tau")
    axes[0].set_ylabel("N")
    axes[0].set_xticks(range(len(lrs)))
    axes[0].set_xticklabels([str(v) for v in lrs], rotation=45)
    axes[0].set_yticks(range(len(Ns)))
    axes[0].set_yticklabels([str(v) for v in Ns])
    fig.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.04)

    im1 = axes[1].imshow(MN, origin="lower", aspect="auto")
    axes[1].set_title("B. M_nonMarkov ridge")
    axes[1].set_xlabel("Delta T / tau")
    axes[1].set_ylabel("N")
    axes[1].set_xticks(range(len(lrs)))
    axes[1].set_xticklabels([str(v) for v in lrs], rotation=45)
    axes[1].set_yticks(range(len(Ns)))
    axes[1].set_yticklabels([str(v) for v in Ns])
    fig.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.04)

    savefig(fig, figs, "fig3_N_lag_ridge")


def plot_optimal_lag(opt: pd.DataFrame, figs: Path):
    fig, ax = plt.subplots(figsize=(4.6, 3.2), constrained_layout=True)
    for metric, marker in [("TE", "o"), ("M_nonMarkov", "s")]:
        g = opt[opt["metric"] == metric].sort_values("N")
        ax.errorbar(g["N"], g["optimal_lag_ratio_mean"], yerr=g["optimal_lag_ratio_sem"], marker=marker, capsize=3, label=metric)
    ax.axhline(1.0, linestyle="--", linewidth=1)
    ax.set_xlabel("Number of bins N")
    ax.set_ylabel("Optimal Delta T / tau")
    ax.set_title("Optimal sampling lag")
    ax.legend(frameon=False)
    savefig(fig, figs, "fig4_optimal_lag_across_N")


def plot_controls(summ: pd.DataFrame, figs: Path):
    order = [
        "main",
        "equilibrium_control",
        "memory_removal_gamma_fast",
        "slow_memory_gamma_slow",
        "no_feedback_beta0",
        "no_hidden_coupling_kappa0",
        "ou_noise",
    ]
    df = summ.copy()
    df["condition"] = pd.Categorical(df["condition"], categories=order, ordered=True)
    df = df.sort_values("condition")
    x = np.arange(len(df))
    labels = [str(v).replace("_", "\n") for v in df["condition"]]

    fig, axes = plt.subplots(1, 2, figsize=(9.0, 3.8), constrained_layout=True)
    axes[0].bar(x, df["TE_mean"], yerr=df["TE_sem"], capsize=3)
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(labels, rotation=45, ha="right")
    axes[0].set_ylabel("Transfer entropy")
    axes[0].set_title("A. Mechanistic controls")

    axes[1].bar(x, df["M_nonMarkov_mean"], yerr=df["M_nonMarkov_sem"], capsize=3)
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(labels, rotation=45, ha="right")
    axes[1].set_ylabel("M_nonMarkov")
    axes[1].set_title("B. Structural memory controls")

    savefig(fig, figs, "fig5_mechanistic_controls")


def plot_nulls(null_summ: pd.DataFrame, mismatch: pd.DataFrame, figs: Path):
    # Null summary panel + mismatched lag TE panel
    fig, axes = plt.subplots(1, 2, figsize=(8.0, 3.3), constrained_layout=True)

    g = null_summ[null_summ["metric"] == "TE"].copy()
    g = g.sort_values("null")
    labels = [str(v).replace("_", "\n") for v in g["null"]]
    x = np.arange(len(g))
    axes[0].bar(x - 0.18, g["observed"], width=0.36, label="Observed")
    axes[0].bar(x + 0.18, g["null_mean"], width=0.36, label="Null mean")
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(labels, rotation=30, ha="right")
    axes[0].set_ylabel("Transfer entropy")
    axes[0].set_title("A. Null models")
    axes[0].legend(frameon=False)

    mm = mismatch.sort_values("past_lag_ratio")
    axes[1].errorbar(mm["past_lag_ratio"], mm["TE_mean"], yerr=mm["TE_sem"], marker="o", capsize=3)
    axes[1].axvline(1.0, linestyle="--", linewidth=1)
    axes[1].set_xscale("log")
    axes[1].set_xlabel("Past lag / tau")
    axes[1].set_ylabel("Transfer entropy")
    axes[1].set_title("B. Past-lag specificity")

    savefig(fig, figs, "fig6_nulls_and_past_lag_specificity")


def plot_partition_and_robustness(part: pd.DataFrame, local: pd.DataFrame, figs: Path):
    fig, axes = plt.subplots(1, 2, figsize=(8.0, 3.3), constrained_layout=True)

    p = part.copy()
    x = np.arange(len(p))
    axes[0].bar(x, p["TE_mean"], yerr=p["TE_sem"], capsize=3)
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(p["partition"], rotation=30, ha="right")
    axes[0].set_ylabel("Transfer entropy")
    axes[0].set_title("A. Partition robustness")

    # Local parameter robustness: TE grouped by parameter/factor
    for param, marker in [("beta", "o"), ("kappa", "s"), ("gamma", "^")]:
        g = local[local["parameter"] == param].sort_values("factor")
        axes[1].errorbar(g["factor"], g["TE_mean"], yerr=g["TE_sem"], marker=marker, capsize=3, label=param)
    axes[1].axvline(1.0, linestyle="--", linewidth=1)
    axes[1].set_xlabel("Parameter multiplier")
    axes[1].set_ylabel("Transfer entropy")
    axes[1].set_title("B. Local parameter robustness")
    axes[1].legend(frameon=False)

    savefig(fig, figs, "fig7_robustness")


# ============================================================
# Report
# ============================================================

def write_report(root: Path, c: Config, runtime: float):
    tables = root / "tables"
    report = root / "RESULTS_SUMMARY.txt"

    def read(name: str):
        p = tables / name
        return pd.read_csv(p) if p.exists() else None

    theory = read("linear_gaussian_theory_TE.csv")
    lag = read("main_lag_summary.csv")
    opt = read("optimal_lag_by_N_summary.csv")
    controls = read("controls_summary.csv")
    nulls = read("null_models_summary.csv")
    mismatch = read("mismatched_past_lag_summary.csv")
    part = read("partition_robustness_summary.csv")
    local = read("local_parameter_robustness_summary.csv")

    with open(report, "w", encoding="utf-8") as f:
        f.write("Non-Markovian predictive information analysis\n")
        f.write(f"Runtime seconds: {runtime:.1f}\n")
        f.write(f"Output folder: {root}\n\n")

        f.write("Primary claim:\n")
        f.write("Hidden finite response generates observable non-Markovian predictive information in a coarse-grained variable.\n")
        f.write("The relevant sampling lag is organized by the hidden relaxation timescale tau.\n\n")

        f.write("Nonlinear finite-response parameters:\n")
        f.write(f"alpha={c.alpha}, beta={c.beta}, gamma={c.gamma}, kappa={c.kappa}, sigma_x={c.sigma_x}, sigma_y={c.sigma_y}\n")
        f.write(f"tau={1.0 / c.gamma}\n\n")

        if theory is not None:
            f.write("Linear-Gaussian analytic TE:\n")
            f.write(theory.to_string(index=False))
            f.write("\n\n")

        if lag is not None:
            f.write("Main lag analysis:\n")
            cols = ["lag_ratio", "TE_mean", "TE_sem", "M_nonMarkov_mean", "M_nonMarkov_sem", "stationarity_distance_mean"]
            f.write(lag[cols].to_string(index=False))
            f.write("\n\n")

        if opt is not None:
            f.write("Optimal lag by N:\n")
            f.write(opt.to_string(index=False))
            f.write("\n\n")

        if controls is not None:
            f.write("Mechanistic controls:\n")
            cols = ["condition", "TE_mean", "TE_sem", "M_nonMarkov_mean", "M_nonMarkov_sem", "stationarity_distance_mean"]
            f.write(controls[cols].to_string(index=False))
            f.write("\n\n")

        if nulls is not None:
            f.write("Null models:\n")
            f.write(nulls.to_string(index=False))
            f.write("\n\n")

        if mismatch is not None:
            f.write("Past-lag specificity:\n")
            f.write(mismatch.to_string(index=False))
            f.write("\n\n")

        if part is not None:
            f.write("Partition robustness:\n")
            f.write(part.to_string(index=False))
            f.write("\n\n")

        if local is not None:
            f.write("Local parameter robustness:\n")
            f.write(local.to_string(index=False))
            f.write("\n\n")

        f.write("Interpretation rules:\n")
        f.write("- TE is the primary predictive-information measure.\n")
        f.write("- M_nonMarkov is the structural companion measure.\n")
        f.write("- No thermodynamic irreversibility, entropy production, or time-arrow claim is made.\n")
        f.write("- Primary support requires TE peak/ridge near DeltaT/tau ~ 1, control reduction, and null collapse.\n\n")

        f.write("Configuration:\n")
        f.write(json.dumps(asdict(c), indent=2, ensure_ascii=False))


# ============================================================
# Main
# ============================================================

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--quick", action="store_true")
    parser.add_argument("--out", type=str, default=None)
    parser.add_argument("--n-runs", type=int, default=None)
    parser.add_argument("--T", type=float, default=None)
    args = parser.parse_args()

    c = quick_config() if args.quick else Config()
    if args.n_runs is not None:
        c.n_runs = args.n_runs
    if args.T is not None:
        c.T = args.T

    set_plot_style()

    if args.out:
        root = Path(args.out).expanduser().resolve()
    else:
        root = Path.home() / "Desktop" / f"nonmarkov_predictive_information_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

    tables = root / "tables"
    figs = root / "figures"
    tables.mkdir(parents=True, exist_ok=True)
    figs.mkdir(parents=True, exist_ok=True)

    with open(root / "config.json", "w", encoding="utf-8") as f:
        json.dump(asdict(c), f, indent=2, ensure_ascii=False)

    start = time.time()
    print(f"Output folder: {root}")

    print("[1/9] Linear-Gaussian analytic theory...")
    theory = run_linear_theory(c, tables)

    print("[2/9] Main simulations...")
    runs = generate_main_runs(c)

    print("[3/9] Main lag analysis...")
    lag_raw, lag_summ = run_lag_analysis(c, runs, tables)

    print("[4/9] N x lag ridge analysis...")
    N_raw, N_summ, opt_raw, opt_summ = run_N_lag_analysis(c, runs, tables)

    print("[5/9] Mechanistic controls...")
    controls_raw, controls_summ = run_controls(c, tables)

    print("[6/9] Null models...")
    null_raw, null_summ = run_null_models(c, runs, tables)

    print("[7/9] Mismatched past-lag specificity...")
    mismatch_raw, mismatch_summ = run_mismatched_lag_analysis(c, runs, tables)

    print("[8/9] Robustness analyses...")
    part_raw, part_summ = run_partition_robustness(c, runs, tables)
    local_raw, local_summ = run_local_parameter_robustness(c, tables)

    print("[9/9] Figures and report...")
    plot_theory(theory, figs)
    plot_lag_curves(lag_summ, figs)
    plot_N_lag_heatmap(N_summ, figs)
    plot_optimal_lag(opt_summ, figs)
    plot_controls(controls_summ, figs)
    plot_nulls(null_summ, mismatch_summ, figs)
    plot_partition_and_robustness(part_summ, local_summ, figs)

    runtime = time.time() - start
    write_report(root, c, runtime)

    print(f"Done. Results saved to: {root}")
    print("Open RESULTS_SUMMARY.txt first.")


if __name__ == "__main__":
    main()
